[general]
caption_extension = ".txt"
shuffle_caption = true
keep_tokens = 1

[[datasets]]
resolution = [1024, 1024]
enable_bucket = true
min_bucket_reso = 512
max_bucket_reso = 2048
bucket_reso_steps = 64

  [[datasets.subsets]]
  image_dir = "data/processed/luna"
  num_repeats = 1

  [[datasets.subsets]]
  image_dir = "data/processed/reg_woman"
  is_reg = true
  num_repeats = 1
  class_tokens = "a woman, photo, portrait"